version: "3.8"

services:
  web:
    build: .
    command: poetry run python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://jatinrohilla:zU3fF8CflE8BMpG4WOSeRIGhVVwWEBy5@dpg-cvl7o1p5pdvs73da1lqg-a/input_form_fullstack
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
