services:
  - type: web
    name: property-station-backend
    env: python
    plan: free
    buildCommand: ./render_build.sh
    startCommand: cd src && gunicorn --worker-class=gevent --workers=4 --bind 0.0.0.0:$PORT core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: property-station-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: property-station-backend.onrender.com,property-station-frontend.onrender.com,ec2-16-170-204-147.eu-north-1.compute.amazonaws.com

databases:
  - name: property-station-db
    plan: free
