services:
  - type: web
    name: input-form-backend
    env: python
    buildCommand: ./build.sh
    startCommand: cd src && gunicorn -c ../gunicorn_config.py core.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://jatinrohilla:zU3fF8CflE8BMpG4WOSeRIGhVVwWEBy5@dpg-cvl7o1p5pdvs73da1lqg-a/input_form_fullstack
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ALLOWED_HOSTS
        value: "input-form-backend.onrender.com,localhost,127.0.0.1,*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-app.vercel.app,http://localhost:5173,http://localhost:3000"
